### PR TITLE
Added custom/2 to handle arbitrary parameters

### PR DESCRIPTION
**Pull request by MisterToolbox**
Since 'run' is declared private, it'd be nice to have a mechanism for arbitrary parameters

### CODE REVIEW

**Comment by route** [comment]
Hey! @MisterToolbox I just declared it private thinking that nobody needs it. We can make it public, anyway I think `custom` isn't a good name for a function like that

**Comment by route** [comment]
I've updated package on hex, likely you need rebase.

**Comment by MisterToolbox** [comment]
I agree - it was a terrible name; just threw together an implementation 'cause i think there's value in having a public function. Thanks!

**Comment by route** [comment]
Yeah totally agree we can make it public if it's useful for people. Feel free to send a PR

**Pull request closed without merging**
