### PR TITLE
Bump v0.3

### PR DESCRIPTION
**Pull request by talklittle**

### CODE REVIEW

**Comment by route** [comment]
👍

**Comment by route** [comment]
Do you know is there a way I can add you to hex.pm?

**Comment by talklittle** [comment]
@route Yes there looks like a command `mix hex.owner add PACKAGE EMAIL` to add other owners. Be aware:

> Package owners have full permissions to the package. They can publish and revert releases and even remove other package owners.

https://hex.pm/docs/tasks

I've sent you an email with my hex.pm email address.

**Comment by route** [comment]
Thanks added!

**Pull request merged**
