### PR TITLE
Fix normalize_arguments to not split space separated params except 'annotate'

### PR DESCRIPTION
**Pull request by kyasu1**
fix normalize_arguments to handle 'annotate' and 'draw' commands separately.

### CODE REVIEW

**Comment by kyasu1** [comment]
Hi I am noob at the Github operations and unintentionally sent this pull request...

However I found a following issue and fixed by a naive approach. Anyway hope you will find a better fix or accept this.

When I was trying this library, I noticed the 'custom' function with 'draw' commands does not draw anything but 'annotate' command show texts fine. I figured out the problem is in handling of 'normalize_arguments' function. It splits params fields with multiple parameters into separate array elements but the 'convert' command does not parse it well then cause an error. On the other hand, ‘annotate’ command expects parameters with its coordinate and text to be drawn separately.

tested on 
Version: ImageMagick 6.9.5-5 Q16 x86_64 2016-08-07 http://www.imagemagick.org
Elixir 1.3.2

**Comment by talklittle** [comment]
Hi can you please fix the unit tests? I think you need to wrap `params` as `to_string(params)` so that it is possible to pass non-string params. For example `custom(image, "raise", 50)`

Other than that, it looks good, thank you for the identification and description of the bug.

**Comment by kyasu1** [comment]
Hi Thank you for your reply. The unit tests failed because of trying to join string and atom types without conversion. They are passing now by wrapping both `option` and `params` with `to_string()` as mentioned by you. Thanks.

**Comment by talklittle** [comment]
Thank you!

**Pull request merged**
