### PR TITLE
Batch operations into single command

### PR DESCRIPTION
**Pull request by talklittle**
ref GH-6

### CODE REVIEW

**Comment by route** [comment]
Thank you! Sorry for a delay

**Comment by route** [comment]
@talklittle maybe I'll add you to repo?

**Comment by talklittle** [comment]
@route Thanks for merging! I am okay being added to the repo. I may want to make a few more small improvements including #15 sometime.

**Comment by route** [comment]
Since it's OS and I'm just a bit limited on time now it's great to have someone else responsible too

**Comment by route** [comment]
You should now have access

**Comment by talklittle** [comment]
@route Cool thank you. I'll continue to submit PRs as usual and hopefully get at least 1 or 2 reviewers before merging anything.

I suppose you'd still be solely in charge of publishing new versions to hex.pm, since the package is tied to your hex.pm account.

**Comment by route** [comment]
Sounds good to me, we'll figure it out

**Pull request merged**
